<div class="j-item-selector fluid-container">
    <div class="page-header">
        <h1 class="main-title">
            <img class="main-logo" src="/img/app/logo.png" alt="Фото на торте!" />

            <small>
                <q class="main-subtitle">Торты на заказ:</q>
                <q class="main-subtitle">Ваш дизайн - наше исполнение!</q>
            </small>
        </h1>
    </div>

    <div id="designer_step"
         class="j-selection-item j-transform-container step current">

        <object id="cake_designer" class="cake-designer-swf"
                classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000">

            <param name="movie" value="/swf/cake-designer.swf">

            <!--[if !IE]>-->
            <object name="cake_designer" class="cake-designer-swf"
                    type="application/x-shockwave-flash"
                    data="/swf/cake-designer.swf" >
            <!--<![endif]-->

                <param name="menu" value="false" />
                <param name="wmode" value="direct" />
                <param name="flashvars" value="variable1=a&variable2=b" />
                <param name="allowfullscreen" value="false" />
                <param name="allowscriptaccess" value="sameDomain" />

                <p>
                    Для конструирования тортика вам необходимо скачать Adobe
                    Flash Player.
                </p>

            <!--[if !IE]>-->
            </object>
            <!--<![endif]-->
        </object>

    </div>

    <div id="share_step" data-init-event="ui-select"
         class="j-selection-item j-transform-container step">

        

    </div>

</div>