<div class="j-item-selector fluid-container">
    <div class="page-header">
        <h1 class="main-title">
            <img class="main-logo" src="/img/app/logo.png"
                 alt="Фото на торте!" />

            <small>
                <q class="main-subtitle">Торты на заказ:</q>
                <q class="main-subtitle">Ваш дизайн - наше исполнение!</q>
            </small>
        </h1>

        <a id="next_step_button"
           class="j-selection-next head-button btn primary large pull-right">
            Дальше &raquo;
        </a>

        <a id="prev_step_button"
           class="j-selection-prev head-button btn primary large pull-right">
            &laquo; Назад
        </a>
    </div>

    <div class="content">
        <div id="designer_step"
             class="j-selection-item j-transform-container step current">

             <?php $this->render('steps/designer') ?>
        </div>

        <div id="share_step" data-init-event="ui-select"
             class="j-selection-item j-transform-container step">

            <?php $this->render('steps/share') ?>
        </div>

        <div id="recipe_step" data-init-event="ui-select"
             data-template-id="recipe_template"
             class="j-selection-item j-transform-container step">

            <?php $this->render('steps/recipe') ?>
        </div>

    </div>
</div>


<div class="hidden">
    <ul>
        <li id="friend_item_renderer" class="j-selection-item">
            <img class="t-userpic userpic" alt="Фото друга"/>
            <span class="t-user-name"></span>
        </li>
        <li id="recipe_renderer">
            <a class="recipe-tile">
                <img class="t-recipe-img t-recipe-id j-popup"
                     alt="Рецепт" width="90" height="90"
                     data-popup-selector="#description_popup"/>

                <label class="recipe-label">
                    <input class="t-recipe-id" type="radio" name="recipe_id" />
                    <span class="t-recipe-name"></span>
                </label>
            </a>
        </li>
    </ul>
</div>

