
<script type="text/javascript" src="/js/src/app/view/main-controller.js"></script>

<script type="text/javascript" src="/js/src/app/view/steps/designer-controller.js"></script>
<script type="text/javascript" src="/js/src/app/view/steps/share-controller.js"></script>

<script src="<?php echo $this->_session->app['api_server'] ?>js/fapi.js" type="text/javascript"></script>

<script type="text/javascript">
    tuna.dom.setSelectorEngine(jQuery.find);
    tuna.view.initMainController();
</script>
