<div id="designer_step" data-init-event="ui-navigate"
     class="j-navigation-page j-control-container row-fluid step">

    <div class="span12 row-fluid">
        <div class="span12">
            <div id="cake_designer" class="j-swf"
                 data-width="650" data-height="630"
                 data-src="/swf/cake-designer.swf">

                <p>Загрузка...</p>
            </div>

            <div class="hide">
                <img id="base_cake_image" class="j-data-image"
                     alt="Загрузка тортика..." width="317" height="317" />
            </div>

            <div>
                <a class="j-navigation-link btn primary large next-btn" data-href="share_step">
                    Сохранить как картинку
                </a>

                <a class="j-navigation-link btn primary large next-btn" data-href="recipe_step">
                    Заказать реальный тортик
                </a>
            </div>
        </div>
    </div>
</div>
