<div class="row">
    <div class="span12">
        <h2>Оформление заказа!</h2>
    </div>
</div>
<form class="j-form" action="/api/" method="POST" target="support_frame">
    <div class="row">
        <div class="span7">
            <div class="j-form-message alert-message hidden"></div>

            <input type="hidden" name="method" value="orders.submit" />
            <input type="hidden" name="format" value="frame-callback" />

            <input class="t-image"  type="hidden" name="image" />
            <input class="t-photo"  type="hidden" name="photo" />
            <input class="t-markup" type="hidden" name="markup" />

            <input class="t-recipe" type="hidden" name="recipe" />
            <input class="t-bakery-id" type="hidden" name="bakery_id" />

            <fieldset>
                <legend>Личная информация</legend>

                <div class="j-name-input clearfix">
                    <label for="name">Имя *</label>
                    <div class="input">
                        <input id="name" name="name" type="text" class="t-user-name" />
                        <span class="j-message help-block">
                            Ваше настоящее имя.
                        </span>
                    </div>
                </div>

                <div class="j-phone-input clearfix">
                    <label for="phone">Телефон *</label>
                    <div class="input">
                        <input id="phone" name="phone" type="text" />
                        <span class="j-message help-block">
                            Чтобы мы могли с вами связаться
                        </span>
                    </div>
                </div>

                <div class="j-email-input clearfix">
                    <label for="email">Email *</label>
                    <div class="input">
                        <input id="email" name="email" type="text" />
                        <span class="j-message help-block">
                            Для подтверждения заказа
                        </span>
                    </div>
                </div>
            </fieldset>

            <fieldset>
                <legend>Информация о доставке</legend>

                <div class="j-address-input clearfix">
                    <label for="address">Адрес *</label>
                    <div class="input">
                        <textarea id="address" name="address" rows="2"></textarea>
                        <span class="j-message help-block">
                            Куда нужно везти торт.
                        </span>
                    </div>
                </div>

                <div class="j-date-input j-time-input clearfix">
                    <label for="date">Дата *</label>
                    <div class="input">
                        <input id="date" class="j-datepicker small" name="date" type="text"/>

                        <select id="time" name="time" class="small-rest">
                            <option value="-1">и время</option>
                            <option value="36000">10:00 - 12:00</option>
                            <option value="43200">12:00 - 14:00</option>
                            <option value="50400">14:00 - 16:00</option>
                            <option value="57600">16:00 - 18:00</option>
                            <option value="64800">18:00 - 20:00</option>
                            <option value="72000">20:00 - 22:00</option>
                        </select>

                        <span class="j-message help-block">
                            Когда нужно везти торт.
                        </span>
                    </div>
                </div>

            </fieldset>
            <fieldset>
                <legend>Дополнительно</legend>

                <div class="j-message-input clearfix">
                    <label for="message">Текст открытки</label>
                    <div class="input">
                        <textarea id="message" name="message" rows="2"></textarea>
                        <span class="j-message help-block">
                            Записка к торту, если, например, торт в подарок.
                        </span>
                    </div>
                </div>

                <div class="j-comment-input clearfix">
                    <label for="comment">Комментарий</label>
                    <div class="input">
                        <textarea id="comment" name="comment" rows="2"></textarea>
                        <span class="j-message help-block">
                            Если вы что-то хотите добавить.
                        </span>
                    </div>
                </div>

            </fieldset>
        </div>
        <div class="span5">
            <div class="cake-image">
                <img class="j-data-image-copy" alt="Загрузка тортика..."
                     data-image-selector="#base_cake_image" />
            </div>

            <div class="cake-price">
                <h3>Цена</h3>

                <table class="condensed-table">
                    <tr>
                        <th>Оформление: </th>
                        <td><span class="t-deco-price">0</span> рублей</td>
                    </tr>
                    <tr>
                        <th>Рецепт: </th>
                        <td><span class="t-recipe-price">0</span> рублей</td>
                    </tr>
                    <tr>
                        <th>Доставка: </th>
                        <td><span class="t-delivery-price">0</span> рублей</td>
                    </tr>
                    <tr>
                        <th>Итого: </th>
                        <td><span class="t-total-price">0</span> рублей</td>
                    </tr>
                </table>
            </div>

            <div class="order-navigation">
                <input type="submit" class="next-btn btn primary large pull-right" value="Заказать!" />

                <a class="j-navigation-link next-btn btn primary large pull-right"
                   data-href="recipe_step">
                    &laquo; Назад
                </a>
            </div>

        </div>
    </div>
    <div class="row">
        <div class="span12">

        </div>
    </div>
</form>

<div class="hidden">
    <tuna:template id="order_template">
        <tuna:attr tuna:name="value" tuna:target="t-image" tuna:path="order/cake/imageBase64" />
        <tuna:attr tuna:name="value" tuna:target="t-photo" tuna:path="order/cake/photoBase64" />
        <tuna:attr tuna:name="value" tuna:target="t-markup" tuna:path="order/cake/markup_json" />

        <tuna:attr tuna:name="value" tuna:target="t-recipe" tuna:path="order/recipe/name" />
        <tuna:attr tuna:name="value" tuna:target="t-bakery-id" tuna:path="order/bakery/id" />

        <tuna:attr tuna:name="value" tuna:target="t-user-name" tuna:path="order/user/name" />

        <tuna:spot tuna:target="t-total-price"    tuna:path="order/payment/totalPrice" />
        <tuna:spot tuna:target="t-deco-price"     tuna:path="order/payment/decoPrice" />
        <tuna:spot tuna:target="t-recipe-price"   tuna:path="order/payment/recipePrice" />
        <tuna:spot tuna:target="t-delivery-price" tuna:path="order/payment/deliveryPrice" />
    </tuna:template>
</div>