<div class="row">
    <div class="span5">
        <h2>Оформление заказа!</h2>
    </div>
    <div class="span7">
        <a id="submit_order_button"
           class="next-btn btn primary large pull-right">
            Заказать!
        </a>
        <a class="j-navigation-link next-btn btn primary large pull-right"
           data-href="recipe_step">
            &laquo; Назад
        </a>
    </div>
</div>

<div class="row">
    <div class="span7">
        <form class="j-form" action="/api/" method="POST" target="support_frame">
            <div class="j-form-message alert-message hidden"></div>

            <input type="hidden" name="method" value="orders.submit" />
            <input type="hidden" name="format" value="frame-callback" />

            <input class="t-image"  type="hidden" name="image" />
            <input class="t-photo"  type="hidden" name="photo" />
            <input class="t-markup" type="hidden" name="markup" />
            <input class="t-recipe" type="hidden" name="recipe" />

            <fieldset>
                <legend>Личная информация</legend>

                <div class="j-name-input clearfix">
                    <label for="name">Имя *</label>
                    <div class="input">
                        <input id="name" name="name" type="text" />
                        <span class="j-message help-block">
                            Ваше настоящее имя.
                        </span>
                    </div>
                </div>

                <div class="j-phone-input clearfix">
                    <label for="phone">Телефон *</label>
                    <div class="input">
                        <input id="phone" name="phone" type="text" />
                        <span class="j-message help-block">
                            Чтобы мы могли с вами связаться
                        </span>
                    </div>
                </div>

                <div class="j-email-input clearfix">
                    <label for="email">Email *</label>
                    <div class="input">
                        <input id="email" name="email" type="text" />
                        <span class="j-message help-block">
                            Для подтверждения заказа
                        </span>
                    </div>
                </div>
            </fieldset>

            <fieldset>
                <legend>Информация о доставке</legend>

                <div class="j-city-input clearfix">
                    <label for="city">Город *</label>
                    <div class="input">
                        <select id="city" name="city" class="t-city-list"></select>
                        <span class="j-message help-block">
                            Пока, только Санкт-Петербург и Москва.
                        </span>
                    </div>
                </div>

                <div class="j-address-input clearfix">
                    <label for="address">Адрес *</label>
                    <div class="input">
                        <textarea id="address" name="address" rows="2"></textarea>
                        <span class="j-message help-block">
                            Стоимость доставки: 450 рублей.
                        </span>
                    </div>
                </div>

                <div class="j-date-input clearfix">
                    <label for="date">Дата *</label>
                    <div class="input">
                        <input id="date" class="j-datepicker" name="date" type="text"/>

                        <span class="j-message help-block">
                            День, в который курьер привезет торт.
                        </span>
                    </div>
                </div>

                <div class="j-time-input clearfix">
                    <label for="time">Время *</label>
                    <div class="input">
                        <select id="time" name="time">
                            <option value="-1"></option>
                            <option value="36000">10:00 - 12:00</option>
                            <option value="43200">12:00 - 14:00</option>
                            <option value="50400">14:00 - 16:00</option>
                            <option value="57600">16:00 - 18:00</option>
                            <option value="64800">18:00 - 20:00</option>
                            <option value="72000">20:00 - 22:00</option>
                        </select>

                        <span class="j-message help-block">
                            Время доставки.
                        </span>
                    </div>
                </div>

                <div class="j-comment-input clearfix">
                    <label for="comment">Комментарий</label>
                    <div class="input">
                        <textarea id="comment" name="comment" rows="2"></textarea>
                        <span class="j-message help-block">
                            Если вы что-то хотите добавить.
                        </span>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
    <div class="span5">
        <div class="cake-image">
            <img class="j-data-image-copy" alt="Загрузка тортика..."
                 data-image-selector="#base_cake_image" />
        </div>

        <div class="cake-price">
            <h3>
                Цена торта:
                <small>
                    <span class="t-price"></span> (+450) рублей.
                </small>
            </h3>
        </div>
    </div>
 </div>

<div class="hidden">
    <select>
        <option id="option_renderer" class="t-value"></option>
    </select>

    <tuna:template id="order_template">
        <tuna:attr tuna:name="value" tuna:target="t-image" tuna:path="cake/image_base64" />
        <tuna:attr tuna:name="value" tuna:target="t-photo" tuna:path="cake/photo_base64" />
        <tuna:attr tuna:name="value" tuna:target="t-markup" tuna:path="cake/markup_json" />
        <tuna:attr tuna:name="value" tuna:target="t-recipe" tuna:path="recipe/name" />

        <tuna:spot tuna:target="t-price" tuna:path="price" />

        <tuna:list tuna:target="t-city-list" tuna:path="cities"
                   tuna:item-renderer-id="option_renderer"
                   tuna:item-template-id="city_item_template"
                   tuna:key-path="$key" />
    </tuna:template>

    <tuna:template id="city_item_template">
        <tuna:attr tuna:name="value" tuna:target="t-value" tuna:path="id" />
        <tuna:spot tuna:target="t-value" tuna:path="name" />
    </tuna:template>
</div>