<div class="row">
    <div class="span12">
        <h2>Выбор рецепта</h2>
    </div>
</div>


<div class="row">
    <div class="span5">
        <div class="cake-info">
            <div class="cake-weight">
                <h3>Вес торта: <small><span class="t-cake-weight">0</span> кг</small></h3>
                <span class="pull-right">
                    <i class="ico ico-persons"></i>
                    <span class="t-cake-persons ico-super">10</span>
                </span>
            </div>

            <div class="cake-image">
                <img class="j-data-image-copy" alt="Загрузка тортика..."
                     data-image-selector="#base_cake_image" />
            </div>

            <div class="recipe-description">
                Чтобы заказать торт необходимо, для начала, выбрать начинку!
            </div>

            <div class="cake-price">
                <h3>Цена</h3>

                <table class="condensed-table">
                    <tr>
                        <th>Оформление: </th>
                        <td><span class="t-deco-price">0</span> рублей</td>
                    </tr>
                    <tr>
                        <th>Рецепт: </th>
                        <td><span class="t-recipe-price">0</span> рублей</td>
                    </tr>
                    <tr>
                        <th>Доставка: </th>
                        <td><span class="t-delivery-price">0</span> рублей</td>
                    </tr>
                    <tr>
                        <th>Итого: </th>
                        <td><span class="t-total-price">0</span> рублей</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="span7">
        <ul class="t-recipes-list media-grid"></ul>

        <a class="j-navigation-link next-btn btn primary large pull-right"
           data-href="order_step">
            Далее &raquo;
        </a>
        <a class="j-navigation-back next-btn btn primary large pull-right">
            &laquo; Назад
        </a>
    </div>
</div>


<div id="city_selection_popup" class="j-autocomplete popup"
     data-template-id="city_autocomplete_template">

     <div class="overlay"></div>
     <div class="modal">
         <div class="modal-header">
             <h3>Где вам нужен торт?</h3>
         </div>
         <div class="modal-body">
            <div class="input clearfix">
                <div class="input-append ">
                    <input id="city_search" type="text"
                           class="j-autocomplete-input" />

                    <label for="city_search" class="add-on btn">v</label>
                </div>
            </div>

            <ul class="j-autocomplete-body t-city-list unstyled hide"></ul>

            <div class="help-block">
                * - если в списке нету вашего города, значит мы
                не можем доставить туда тортик.
            </div>
         </div>
         <div class="modal-footer">
             <a id="city_ok_button" href="#" class="j-popup-apply btn primary disabled">ОК</a>
             <a href="#" class="j-navigation-back j-popup-close btn">Назад</a>
         </div>
     </div>
 </div>

<div id="recipe_description_popup" class="popup">
    <div class="overlay"></div>
    <div class="modal">
        <div class="modal-header">
            <a href="#" class="j-popup-close close">×</a>
            <h3 class="t-popup-recipe-name"></h3>
        </div>
        <div class="modal-body">
            <p class="t-popup-recipe-desc"></p>
        </div>
        <div class="modal-footer">
            <a href="#" class="j-popup-apply btn primary">Выбрать</a>
            <a href="#" class="j-popup-close btn">Закрыть</a>
        </div>
    </div>
</div>

<div class="hide">
    <tuna:template id="recipe_template">
        <tuna:spot tuna:target="t-cake-weight"  tuna:path="order/cake/weight" />
        <tuna:spot tuna:target="t-cake-persons" tuna:path="order/cake/personsCount" />

        <tuna:spot tuna:target="t-total-price"    tuna:path="order/payment/totalPrice" />
        <tuna:spot tuna:target="t-deco-price"     tuna:path="order/payment/decoPrice" />
        <tuna:spot tuna:target="t-recipe-price"   tuna:path="order/payment/recipePrice" />
        <tuna:spot tuna:target="t-delivery-price" tuna:path="order/payment/deliveryPrice" />

        <tuna:spot tuna:target="t-popup-recipe-name" tuna:path="popup_recipe/name" />
        <tuna:spot tuna:target="t-popup-recipe-desc" tuna:path="popup_recipe/desc" />

        <tuna:list tuna:target="t-recipes-list" tuna:path="recipes"
                   tuna:item-renderer-id="recipe_renderer"
                   tuna:item-template-id="recipe_item_template"
                   tuna:key-path="$key" />
    </tuna:template>

    <tuna:template id="recipe_item_template">
        <tuna:attr tuna:target="t-recipe-img" tuna:path="imageUrl" tuna:name="src"/>
        <tuna:attr tuna:target="t-recipe-img" tuna:path="name" tuna:name="alt"/>
        
        <tuna:attr tuna:target="t-recipe-index" tuna:path="$key" tuna:name="data-index" />
        <tuna:attr tuna:target="t-recipe-input" tuna:path="$key" tuna:name="value" />

        <tuna:spot tuna:target="t-recipe-name" tuna:path="name" />
    </tuna:template>

    <tuna:template id="city_autocomplete_template">
        <tuna:list tuna:target="t-city-list" tuna:path=""
                   tuna:item-renderer-id="city_item_renderer"
                   tuna:item-template-id="city_item_template"
                   tuna:key-path="$key" />
    </tuna:template>

    <tuna:template id="city_item_template">
        <tuna:spot tuna:target="t-name" tuna:path="city" />
    </tuna:template>

</div>