<ul class="unstyled share-menu">
    <li>
       <img class="j-data-image-copy" alt="Загрузка тортика..."
            data-image-selector="#base_cake_image" width="317" height="317" />
    </li>
    <li>
       <a id="wall_post_link" class="btn primary large">
           Запостить на стену
       </a>
    </li>
    <li>
        <a class="j-friends-popup j-popup btn primary large"
           data-popup-selector="#friend_list_popup">
            Послать другу
        </a>
    </li>
    <li>
        <form action="/api/" target="_blank" method="POST">
            <input type="hidden" name="method" value="utils.base64Echo" />
            <input type="hidden" name="type" value="image/jpeg" />
            <input type="hidden" name="is_downloading" value="true" />
            <input id="download_data_input" type="hidden" name="data" />
            <input type="submit" class="btn primary large" value="Скачать" />
        </form>
    </li>
    <li>
        <a class="j-navigation-link btn primary large" data-href="designer_step">
            &laquo; Назад
        </a>
    </li>
</ul>

<div id="friend_list_popup" class="j-filtration popup"
     data-template-id="friends_autocomplete_template">

    <div class="overlay"></div>
    <div class="modal">
        <div class="modal-header friends-popup-header">
            <h3 class="friends-popup-title">Выберите кому отослать!</h3>

            <label class="friends-search">
                <input class="j-filtration-input"
                       type="text" placeholder="Имя друга" />
            </label>
        </div>
        <div class="modal-body friend-list-overlay">
            <ul class="t-friend-list friend-list unstyled"></ul>
        </div>
        <div class="modal-footer">
            <a href="#" class="j-popup-close btn">Закрыть</a>
        </div>
    </div>
</div>


<div class="hidden">
    <tuna:template id="friends_autocomplete_template">
        <tuna:list tuna:target="t-friend-list" tuna:path=""
                   tuna:item-renderer-id="friend_item_renderer"
                   tuna:item-template-id="friend_item_template"
                   tuna:key-path="$key" />
    </tuna:template>

    <tuna:template id="friend_item_template">
        <tuna:spot tuna:target="t-user-name" tuna:path="name" />
        <tuna:attr tuna:target="t-userpic" tuna:name="src"
                   tuna:path="userpicUrl" />

        <tuna:attr tuna:target="t-user-id" tuna:name="data-user-id"
                   tuna:path="id" />
    </tuna:template>
</div>

