<div id="title_step" class="j-navigation-page
                            j-control-container
                            row-fluid step active">

    <div class="span12 row-fluid">
        <?php if ($this->request->get('network') !== NULL) {?>
            <div class="span5">
                <?php $this->render('steps/title/intro'); ?>
            </div>
            <div class="span7">
                <?php $this->render('steps/title/cake-list'); ?>
            </div>
        <?php } else { ?>
            <div class="span3">
                <?php $this->render('steps/title/intro'); ?>
            </div>
            <div class="span9 row-fluid">
                <div class="span7">
                    <?php $this->render('steps/title/cake-list'); ?>
                </div>
                <div class="span5">
                    <?php $this->render('steps/title/comments'); ?>
                </div>
            </div>
        <?php } ?>
    </div>

    <hr />

    <?php $this->render('steps/title/gallery'); ?>

    <div id="cake_image_popup" class="hide">
         <div class="modal-backdrop"></div>
         <div class="modal">
             <div class="modal-header">
                <h3>Тортик до и после</h3>
             </div>
             <div class="modal-body">
                 <div class="image-container">
                     <img class="j-cake-image-photo" alt="Фото" />
                     <img class="j-cake-image-before" alt="До" />
                     <img class="j-cake-image-after" alt="После" />
                 </div>
             </div>
             <div class="modal-footer">
                 <a href="#" class="j-popup-close btn">Закрыть</a>
             </div>
         </div>
    </div>
</div>
