<div class="row">
    <div class="span7">
        <div class="title-image">
            <img class="j-navigation-link" data-href="designer_step"
                 src="/img/title.jpg" alt="Тортик" width="330" height="330" />
        </div>
    </div>
    <div class="span4">
        <div class="application-intro">
            <h3>Никогда не пекли тортики?</h3>
            <p>
                Фантазируйте и создавайте дизайн Вашего тортика сами с помощью
                конструктора тортиков! И, если захотите, профессиональное
                кондитерское производство воспроизведет Ваш дизайн в настоящем
                торте, который будет вовремя доставлен к месту Вашего праздника.
            </p>
            <p>
                <a class="j-navigation-link btn primary large"
                   data-href="designer_step">
                    Начнем &raquo;
                </a>
            </p>
        </div>
    </div>
</div>

<hr />
        
<div class="row">
    <div class="span14 carousel cake-gallery">
        <h3>Галерея тортиков <small>(наведите мышку)</small></h3>
        <h4><a class="j-cake-image-popup" data-cake-index="4">
            Как мы это делаем?
        </a></h4>

        <ul class="j-selection-group media-grid cake-gallery-body"
            data-selection-event="mouseover">

            <li class="j-selection-item active j-cake-image-popup"
                data-cake-index="1">

                <a>
                    <span class="expand-item">
                        <span class="image-box image-center">
                            <img class="expanded-image vertical" alt="Фото"
                                 src="/img/title/photo_small_1.jpg" />
                        </span>
                    </span>
                    <span class="expand-item second">
                        <span class="image-box image-center">
                            <img class="expanded-image vertical" alt="До"
                                 src="/img/title/before_small_1.jpg" />
                        </span>
                    </span>
                    <span class="expand-item third">
                        <span class="image-box image-center">
                            <img class="expanded-image horizontal" alt="После"
                                 src="/img/title/after_small_1.jpg" />
                        </span>
                    </span>
                </a>
            </li>

            <li class="j-selection-item j-cake-image-popup" data-cake-index="2">
                <a>
                    <span class="expand-item">
                        <span class="image-box image-center">
                            <img class="expanded-image horizontal" alt="Фото"
                                 src="/img/title/photo_small_2.jpg" />
                        </span>
                    </span>
                    <span class="expand-item second">
                        <span class="image-box image-center">
                            <img class="expanded-image vertical" alt="До"
                                 src="/img/title/before_small_2.jpg" />
                        </span>
                    </span>
                    <span class="expand-item third">
                        <span class="image-box image-center">
                            <img class="expanded-image horizontal" alt="После"
                                 src="/img/title/after_small_2.jpg"  />
                        </span>
                    </span>
                </a>
            </li>

            <li class="j-selection-item j-cake-image-popup" data-cake-index="3">
                <a>
                    <span class="expand-item">
                        <span class="image-box image-center">
                            <img class="expanded-image vertical" alt="Фото"
                                 src="/img/title/photo_small_3.jpg" />
                        </span>
                    </span>
                    <span class="expand-item second">
                        <span class="image-box image-center">
                            <img class="expanded-image horizontal" alt="До"
                                 src="/img/title/before_small_3.jpg" />
                        </span>
                    </span>
                    <span class="expand-item third">
                        <span class="image-box image-center">
                            <img class="expanded-image vertical" alt="После"
                                 src="/img/title/after_small_3.jpg" />
                        </span>
                    </span>
                </a>
            </li>

        </ul>
    </div>
</div>

<div id="cake_image_popup" class="popup">
     <div class="overlay"></div>
     <div class="modal">
         <div class="modal-header">
            <h3>Тортик до и после</h3>
         </div>
         <div class="modal-body">
             <div class="image-container">
                 <img class="j-cake-image-photo" alt="Фото" />
                 <img class="j-cake-image-before" alt="До" />
                 <img class="j-cake-image-after" alt="После" />
             </div>
         </div>
         <div class="modal-footer">
             <a href="#" class="j-popup-close btn">Закрыть</a>
         </div>
     </div>
 </div>