<ul class="thumbnails">
    <li>
      <div class="thumbnail">
          <div class="cake-image-box">
              <img src="http://files.fotonatorte.ru/cake_image_4f3b568ed2e26.jpg"
                   alt="Тортик" width="110" height="110" />

              <div class="cake-price">
                  <span>
                    <del>1700 руб.</del> <br /> 1400 руб.
                  </span>
              </div>
          </div>
          <div class="cake-info">
              <span class="">1 кг.</span>
              <span class="j-navigation-link btn small pull-right primary"
                    data-href="order_step" data-weight="1" data-price="1400"
                    data-image="http://files.fotonatorte.ru/cake_image_4f3b568ed2e26.jpg">
                  Хочу!
              </span>
          </div>
      </div>
    </li>

    <li>
        <div class="thumbnail">
            <div class="cake-image-box">
                <img src="http://files.fotonatorte.ru/cake_image_4f2be1b0f23b5.jpg" alt="Тортик"
                     width="110" height="110" />

                <div class="cake-price">
                    <span>
                      <del>1700 руб.</del> <br /> 1400 руб.
                    </span>
                </div>
            </div>

            <div class="cake-info">
                <span class="">1 кг.</span>
                <span class="j-navigation-link btn small pull-right primary"
                      data-href="order_step" data-weight="1" data-price="1400"
                      data-image="http://files.fotonatorte.ru/cake_image_4f2be1b0f23b5.jpg">
                    Хочу!
                </span>
            </div>
        </div>
    </li>

    <li>
        <div class="thumbnail">
           <div class="cake-image-box">
               <img src="http://files.fotonatorte.ru/cake_image_4f3b575be99ba.jpg" alt="Тортик"
                    width="110" height="110" />
               <div class="cake-price">
                   <span>
                     <del>1700 руб.</del> <br /> 1400 руб.
                   </span>
               </div>
           </div>

           <div class="cake-info">
               <span class="">1 кг.</span>
               <span class="j-navigation-link btn small pull-right primary"
                     data-href="order_step" data-weight="1" data-price="1400"
                     data-image="http://files.fotonatorte.ru/cake_image_4f3b575be99ba.jpg">
                   Хочу!
               </span>
           </div>
        </div>
    </li>

    <li>
        <div class="thumbnail">
           <div class="cake-image-box">
               <img src="http://files.fotonatorte.ru/cake_image_4f3b5bafbd4cd.jpg" alt="Тортик"
                    width="110" height="110" />
               <div class="cake-price">
                   <span>
                     <del>1700 руб.</del> <br /> 1400 руб.
                   </span>
               </div>
           </div>

           <div class="cake-info">
               <span class="">1 кг.</span>
               <span class="j-navigation-link btn small pull-right primary"
                     data-href="order_step" data-weight="1" data-price="1400"
                     data-image="http://files.fotonatorte.ru/cake_image_4f3b5bafbd4cd.jpg">
                   Хочу!
               </span>
           </div>
        </div>
    </li>

    <li>
        <div class="thumbnail">
            <div class="cake-image-box">
                <img src="http://files.fotonatorte.ru/cake_image_4f3b5c6750e99.jpg" alt="Тортик"
                     width="110" height="110" />
                <div class="cake-price">
                    <span>
                      <del>1700 руб.</del> <br /> 1400 руб.
                    </span>
                </div>
            </div>

            <div class="cake-info">
                <span class="">1 кг.</span>
                <span class="j-navigation-link btn small pull-right primary"
                      data-href="order_step" data-weight="1" data-price="1400"
                      data-image="http://files.fotonatorte.ru/cake_image_4f3b5c6750e99.jpg">
                    Хочу!
                </span>
            </div>
        </div>
    </li>

    <li>
        <div class="thumbnail">
            <div class="cake-image-box">
                <img src="http://files.fotonatorte.ru/cake_image_4f3b5cfe290ef.jpg" alt="Тортик"
                     width="110" height="110" />
                <div class="cake-price">
                    <span>
                      <del>1700 руб.</del> <br /> 1400 руб.
                    </span>
                </div>
            </div>

            <div class="cake-info">
                <span class="">1 кг.</span>
                <span class="j-navigation-link btn small pull-right primary"
                      data-href="order_step" data-weight="1" data-price="1400"
                      data-image="http://files.fotonatorte.ru/cake_image_4f3b5cfe290ef.jpg">
                    Хочу!
                </span>
            </div>
        </div>
    </li>

    <li>
        <div class="thumbnail">
            <div class="cake-image-box">
                <img src="http://files.fotonatorte.ru/cake_image_4f2bcf835adb9.jpg" alt="Тортик"
                     width="110" height="110" />
                <div class="cake-price">
                    <span>
                      <del>1700 руб.</del> <br /> 1400 руб.
                    </span>
                </div>
            </div>

            <div class="cake-info">
                <span class="">1 кг.</span>
                <span class="j-navigation-link btn small pull-right primary"
                      data-href="order_step" data-weight="1" data-price="1400"
                      data-image="http://files.fotonatorte.ru/cake_image_4f2bcf835adb9.jpg">
                    Хочу!
                </span>
            </div>
        </div>
    </li>
    <li>
        <div class="thumbnail">
            <div class="cake-image-box">
                <img src="http://files.fotonatorte.ru/cake_image_4f3b5f23e3596.jpg" alt="Тортик"
                     width="110" height="110" />
                <div class="cake-price">
                    <span>
                      <del>1700 руб.</del> <br /> 1400 руб.
                    </span>
                </div>
            </div>

            <div class="cake-info">
                <span class="">1 кг.</span>
                <span class="j-navigation-link btn small pull-right primary"
                      data-href="order_step" data-weight="1" data-price="1400"
                      data-image="http://files.fotonatorte.ru/cake_image_4f3b5f23e3596.jpg">
                    Хочу!
                </span>
            </div>
        </div>
    </li>

    <li>
        <div class="thumbnail">
            <div class="cake-image-box">
                <img src="http://files.fotonatorte.ru/cake_image_4f2bd57a52b6e.jpg" alt="Тортик"
                     width="110" height="110" />
                <div class="cake-price"><span>3000 руб.</span></div>
            </div>

            <div class="cake-info">
                <span class="">2 кг.</span>
                <span class="j-navigation-link btn small pull-right primary"
                      data-href="order_step" data-weight="2" data-price="3000"
                      data-image="http://files.fotonatorte.ru/cake_image_4f2bd57a52b6e.jpg">
                    Хочу!
                </span>
            </div>
        </div>
    </li>
</ul>
