<div class="alert alert-info alert-block">
    <img src="http://placehold.it/60x60" alt="Тортик" width="60" height="60" />
    
    <h3 class="alert-heading">Вай-вай-вай</h3>
    Тортик тортик тортик тортик тортик тортик тортик тортик тортик тортик тортик
    тортик тортик тортик тортик тортик тортик тортик тортик тортик тортик тортик
</div>
<div class="alert alert-info alert-block">
    <img src="http://placehold.it/60x60" alt="Тортик" width="60" height="60" />

    <h3 class="alert-heading">Вай-вай-вай</h3>
    Тортик тортик тортик тортик тортик тортик тортик тортик тортик тортик тортик
    тортик тортик тортик тортик тортик тортик тортик тортик тортик тортик тортик
</div>
<div class="alert alert-info alert-block">
    <img src="http://placehold.it/60x60" alt="Тортик" width="60" height="60" />

    <h3 class="alert-heading">Вай-вай-вай</h3>
    Тортик тортик тортик тортик тортик тортик тортик тортик тортик тортик тортик
    тортик тортик тортик тортик тортик тортик тортик тортик тортик тортик тортик
</div>