<div class="alert alert-comment alert-block">
    <h3>Федоров Сергей Анатольевич</h3>

    <blockquote>
        <img src="/img/comments/comment_1.png" alt="Тортик"
             width="55" height="55" />
        Всё отлично, но мало: ТОРТ ВКУСНЫЙ, дочка довольна! Скоро у жены д/р,
        буду думать.
    </blockquote>

    <address>Менеджер отдела продаж <br /> ООО "ОптКрепеж"</address>
</div>

<div class="alert alert-comment alert-block">
    <h3>Ольга Васильева</h3>

    <blockquote>
        <img src="/img/comments/comment_2.png" alt="Тортик"
             width="55" height="55" />
        Спасибо, торт был чудесным! Завтра у нас в редакции в прямом
        эфире с 15.00-16.00 будет выступать вратарь "Зенита" - Малафеев.
        Возможно ли сделать торт сверху написать  «Аиф Онлайн»,
        а посередине его фотографию?
    </blockquote>

    <address>
        Менеджер по рекламе <br />
        ЗАО "Аргументы и факты - Петербург"
    </address>
</div>