<div class="row-fluid">
    <div class="span6">
        <h3>Галерея тортиков <small>(наведите мышку)</small></h3>
    </div>
    <div class="span6">
        <h3 class="pull-right">
            <a href="#" class="j-popup-button"
               data-popup-selector="#howto_popup">
                Как мы это делаем?
            </a>
        </h3>
    </div>
</div>

<div class="j-selection-group row-fluid"
     data-selection-event="mouseover">

    <div class="span12 carousel cake-gallery">
        <ul class="thumbnails cake-gallery-body">
            <li class="j-selection-item j-cake-image-popup active" data-cake-index="1">

                <div class="thumbnail">
                    <span class="expand-item">
                        <span class="image-box image-center">
                            <img class="expanded-image vertical" alt="Фото"
                                 src="/img/title/photo_small_1.jpg" />
                        </span>
                    </span>
                    <span class="expand-item second">
                        <span class="image-box image-center">
                            <img class="expanded-image vertical" alt="До"
                                 src="/img/title/before_small_1.jpg" />
                        </span>
                    </span>
                    <span class="expand-item third">
                        <span class="image-box image-center">
                            <img class="expanded-image horizontal" alt="После"
                                 src="/img/title/after_small_1.jpg" />
                        </span>
                    </span>
                </div>
            </li>
            <li class="j-selection-item j-cake-image-popup" data-cake-index="2">
                <div class="thumbnail">
                    <span class="expand-item">
                        <span class="image-box image-center">
                            <img class="expanded-image horizontal" alt="Фото"
                                 src="/img/title/photo_small_2.jpg" />
                        </span>
                    </span>
                    <span class="expand-item second">
                        <span class="image-box image-center">
                            <img class="expanded-image vertical" alt="До"
                                 src="/img/title/before_small_2.jpg" />
                        </span>
                    </span>
                    <span class="expand-item third">
                        <span class="image-box image-center">
                            <img class="expanded-image horizontal" alt="После"
                                 src="/img/title/after_small_2.jpg"  />
                        </span>
                    </span>
                </div>
            </li>
            <li class="j-selection-item j-cake-image-popup" data-cake-index="3">
                <div class="thumbnail">
                    <span class="expand-item">
                        <span class="image-box image-center">
                            <img class="expanded-image vertical" alt="Фото"
                                 src="/img/title/photo_small_3.jpg" />
                        </span>
                    </span>
                    <span class="expand-item second">
                        <span class="image-box image-center">
                            <img class="expanded-image horizontal" alt="До"
                                 src="/img/title/before_small_3.jpg" />
                        </span>
                    </span>
                    <span class="expand-item third">
                        <span class="image-box image-center">
                            <img class="expanded-image vertical" alt="После"
                                 src="/img/title/after_small_3.jpg" />
                        </span>
                    </span>
                </div>
            </li>
        </ul>
    </div>
</div>

<div id="howto_popup" class="hide">
    <div class="modal-backdrop"></div>
    <div class="howto-popup modal">
        <div class="modal-header">
            <h3>Как мы это делаем?</h3>
        </div>
        <div class="modal-body">
            <img src="img/info.jpg" alt="Как мы это делаем?" width="1200" height="1000" />
        </div>
        <div class="modal-footer">
            <a href="#" class="j-popup-close btn">Закрыть</a>
        </div>
    </div>
</div>