<div class="row-fluid">
    <div class="span6">
        <h3>Галерея тортиков <small>(наведите мышку)</small></h3>
    </div>
    <div class="span6">
        <h3 class="pull-right">
            <a href="#" class="j-cake-image-popup" data-cake-index="4">
                Как мы это делаем?
            </a>
        </h3>
    </div>
</div>

<div class="row-fluid">
    <div class="span12 carousel cake-gallery">
        <ul class="j-selection-group thumbnails cake-gallery-body"
            data-selection-event="mouseover">

            <li class="j-selection-item active j-cake-image-popup"
                data-cake-index="1">

                <div class="thumbnail">
                    <span class="expand-item">
                        <span class="image-box image-center">
                            <img class="expanded-image vertical" alt="Фото"
                                 src="/img/title/photo_small_1.jpg" />
                        </span>
                    </span>
                    <span class="expand-item second">
                        <span class="image-box image-center">
                            <img class="expanded-image vertical" alt="До"
                                 src="/img/title/before_small_1.jpg" />
                        </span>
                    </span>
                    <span class="expand-item third">
                        <span class="image-box image-center">
                            <img class="expanded-image horizontal" alt="После"
                                 src="/img/title/after_small_1.jpg" />
                        </span>
                    </span>
                </div>
            </li>

            <li class="j-selection-item j-cake-image-popup" data-cake-index="2">
                <div class="thumbnail">
                    <span class="expand-item">
                        <span class="image-box image-center">
                            <img class="expanded-image horizontal" alt="Фото"
                                 src="/img/title/photo_small_2.jpg" />
                        </span>
                    </span>
                    <span class="expand-item second">
                        <span class="image-box image-center">
                            <img class="expanded-image vertical" alt="До"
                                 src="/img/title/before_small_2.jpg" />
                        </span>
                    </span>
                    <span class="expand-item third">
                        <span class="image-box image-center">
                            <img class="expanded-image horizontal" alt="После"
                                 src="/img/title/after_small_2.jpg"  />
                        </span>
                    </span>
                </div>
            </li>

            <li class="j-selection-item j-cake-image-popup" data-cake-index="3">
                <div class="thumbnail">
                    <span class="expand-item">
                        <span class="image-box image-center">
                            <img class="expanded-image vertical" alt="Фото"
                                 src="/img/title/photo_small_3.jpg" />
                        </span>
                    </span>
                    <span class="expand-item second">
                        <span class="image-box image-center">
                            <img class="expanded-image horizontal" alt="До"
                                 src="/img/title/before_small_3.jpg" />
                        </span>
                    </span>
                    <span class="expand-item third">
                        <span class="image-box image-center">
                            <img class="expanded-image vertical" alt="После"
                                 src="/img/title/after_small_3.jpg" />
                        </span>
                    </span>
                </div>
            </li>

        </ul>
    </div>
</div>
