<div class="row">
    <div class="span5">
        <h2>Оформление заказа!</h2>
    </div>
    <div class="span7">
        <a id="submit_order_button" data-href="result_step"
           class=" next-btn btn primary large"> <!-- j-navigation-link -->
            Заказать!
        </a>
    </div>
</div>

<div class="row">
    <div class="span7">
        <form class="j-form" action="/api/" method="POST" target="support_frame">
            <div class="j-form-message alert-message hidden"></div>

            <input type="hidden" name="method" value="order.submit" />
            <input type="hidden" name="format" value="frame-callback" />

            <input id="cake_image_data" type="hidden" name="image_data" />
            <input id="cake_photo_data" type="hidden" name="photo_data" />

            <fieldset>
                <legend>Личная информация</legend>

                <div class="j-name-input clearfix">
                    <label for="name">Имя *</label>
                    <div class="input">
                        <input id="name" name="name" type="text" class="t-user-name" />
                        <span class="j-message help-block">
                            Ваше настоящее имя.
                        </span>
                    </div>
                </div>

                <div class="j-phone-input clearfix">
                    <label for="phone">Телефон *</label>
                    <div class="input">
                        <input id="phone" name="phone" type="text" />
                        <span class="j-message help-block">
                            Чтобы мы могли с вами связаться
                        </span>
                    </div>
                </div>

                <div class="j-email-input clearfix">
                    <label for="email">Email *</label>
                    <div class="input">
                        <input id="email" name="email" type="text" />
                        <span class="j-message help-block">
                            Для подтверждения заказа
                        </span>
                    </div>
                </div>
            </fieldset>

            <fieldset>
                <legend>Информация о доставке</legend>

                <div class="j-address-input clearfix">
                    <label for="address">Адрес *</label>
                    <div class="input">
                        <textarea id="address" name="address" rows="3"></textarea>
                        <span class="j-message help-block">
                            Адрес, куда доставлять торт. Пока, только
                            Санкт-Петербург.
                        </span>
                    </div>
                </div>

                <div class="j-day-input clearfix">
                    <label for="day">Дата *</label>
                    <div class="input">
                        <select id="day" name="day" class="micro">
                            <option value="1">1</option>
                            <option value="2">1</option>
                        </select> \
                        <select name="month" class="small">
                            <option value="01">Январь</option>
                            <option value="02">Февраль</option>
                            <option value="03">Март</option>
                            <option value="04">Апрель</option>
                            <option value="05">Май</option>
                            <option value="06">Июнь</option>
                            <option value="07">Июль</option>
                            <option value="08">Август</option>
                            <option value="09">Сентябрь</option>
                            <option value="10">Октябрь</option>
                            <option value="11">Ноябрь</option>
                            <option value="12">Декабрь</option>
                        </select> \
                        <select name="year" class="mini">
                            <option value="2011">2011</option>
                            <option value="2012">2012</option>
                        </select>
                        <span class="j-message help-block">
                            День, в который курьер привезет торт.
                        </span>
                    </div>
                </div>

                <div class="j-comment-input clearfix">
                    <label for="comment">Комментарий</label>
                    <div class="input">
                        <textarea id="comment" name="comment" rows="3"></textarea>
                        <span class="j-message help-block">
                            Дополнительная информация. Например, комментарий
                            курьеру.
                        </span>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
    <div class="span5">
        <div class="cake-price">
            <h3>
                Цена торта: <small class="t-cake-price">1000 рублей</small>
            </h3>
        </div>
        <div class="cake-image">
            <img class="j-data-image-copy" alt="Загрузка тортика..."
                 data-image-selector="#base_cake_image" />
        </div>
    </div>
 </div>

<div class="hidden">
    <tuna:template id="order_template">
        <tuna:spot tuna:target="t-cake-weight"  tuna:path="cake/weight" />
        <tuna:spot tuna:target="t-cake-persons"  tuna:path="cake/persons_count" />
        <tuna:spot tuna:target="t-cake-price" tuna:path="cake/price" />

        <tuna:spot tuna:target="t-popup-recipe-name" tuna:path="popup_recipe/name" />
        <tuna:spot tuna:target="t-popup-recipe-desc" tuna:path="popup_recipe/id" />

        <tuna:list tuna:target="t-recipes-list" tuna:path="recipes"
                   tuna:item-renderer-id="recipe_renderer"
                   tuna:item-template-id="recipe_item_template"
                   tuna:key-path="$key" />
    </tuna:template>
</div>