<h2>Выбор рецепта</h2>
    
<div class="row">
    <div class="span5">
        <div class="cake-info">
            <div class="cake-weight">
                <h3>Вес торта: <small class="t-cake-weight">5 кг</small></h3>
                <span class="pull-right">
                    <i class="ico ico-persons"></i>
                    <span class="t-cake-persons ico-super">10</span>
                </span>
            </div>

            <div class="cake-image">
                <img id="recipe_cake_image" alt="Загрузка тортика..." />
            </div>

            <div class="recipe-description">
                Чтобы заказать торт необходимо, для начала, выбрать начинку!
            </div>

            <div class="cake-price">
                <h3>
                    Цена торта: <small class="t-cake-price">100 рублей</small>
                </h3>
            </div>
        </div>
    </div>
    <div class="span7">
        <ul class="t-recipes-list media-grid"></ul>
    </div>
</div>

<div id="recipe_description_popup" class="popup">
    <div class="overlay"></div>
    <div class="modal">
        <div class="modal-header">
            <a href="#" class="j-popup-close close">×</a>
            <h3 class="t-popup-recipe-name"></h3>
        </div>
        <div class="modal-body">
            <p class="t-popup-recipe-desc"></p>
        </div>
        <div class="modal-footer">
            <a href="#" class="j-popup-apply btn primary">Выбрать</a>
            <a href="#" class="j-popup-close btn">Закрыть</a>
        </div>
    </div>
</div>

<div class="hidden">
    <tuna:template id="recipe_template">
        <tuna:spot tuna:target="t-cake-weight"  tuna:path="cake/weight" />
        <tuna:spot tuna:target="t-cake-persons"  tuna:path="cake/persons_count" />
        <tuna:spot tuna:target="t-cake-price" tuna:path="cake/price" />

        <tuna:spot tuna:target="t-popup-recipe-name" tuna:path="popup_recipe/name" />
        <tuna:spot tuna:target="t-popup-recipe-desc" tuna:path="popup_recipe/id" />

        <tuna:list tuna:target="t-recipes-list" tuna:path="recipes"
                   tuna:item-renderer-id="recipe_renderer"
                   tuna:item-template-id="recipe_item_template"
                   tuna:key-path="$key" />
    </tuna:template>

    <tuna:template id="recipe_item_template">
        <tuna:attr tuna:target="t-recipe-img" tuna:path="image_url" tuna:name="src"/>
        <tuna:attr tuna:target="t-recipe-img" tuna:path="name" tuna:name="alt"/>
        
        <tuna:attr tuna:target="t-recipe-index" tuna:path="$key" tuna:name="data-index" />
        <tuna:attr tuna:target="t-recipe-input" tuna:path="$key" tuna:name="value" />

        <tuna:spot tuna:target="t-recipe-name" tuna:path="name" />
    </tuna:template>
</div>