<h2>Выбор рецепта</h2>
    
<div class="row">
    <div class="span5">
        <div class="cake-info">
            <div class="cake-weight">
                <h3>Вес торта: <small class="t-cake-weight">5 кг</small></h3>
                <span class="pull-right">
                    <i class="ico ico-persons"></i>
                    <span class="t-cake-persons ico-super">10</span>
                </span>
            </div>

            <div class="cake-image">
                <img width="240" height="240" />
            </div>

            <div class="recipe-description">
                Чтобы заказать торт необходимо, для начала, выбрать начинку!
            </div>

            <div class="cake-price">
                <h3>Цена торта: <small class="t-cake-price">100 рублей</small></h3>
            </div>
        </div>
    </div>
    <div class="span7">
        <ul class="t-recipes-list media-grid"></ul>
    </div>
</div>