<ul class="unstyled share-menu">
    <li>
       <img id="share_cake_image" class="j-data-image"
            alt="Загрузка тортика..." width="317" height="317" />
    </li>
    <li>
       <a id="wall_post_link" class="btn primary large">
           Запостить на стену
       </a>
    </li>
    <li>
        <a class="j-popup btn primary large"
           data-popup-selector="#friend_list_popup">
            Послать другу
        </a>
    </li>
    <li>
        <form action="api/?method=utils.echoImage"
              target="_blank" method="POST">
            
            <input type="hidden" name="type" value="image/jpeg" />
            <input type="hidden" name="is_downloading" value="true" />
            <input id="download_data_input" type="hidden" name="data" />

            <input type="submit" class="download-button btn primary large"
                   value="Сохранить" />
        </form>
        
    </li>
</ul>

<div id="friend_list_popup"
     class="j-item-selector j-transform-container popup"
     data-template-id="friends_popup_template">

    <div class="overlay"></div>
    <div class="modal">
        <div class="modal-header friends-popup-header">
            <a href="#" class="j-popup-close close">&times;</a>
            <h3 class="friends-popup-title">Выберите друга!</h3>

            <label class="friends-search">
                <input id="friend_search_input" type="text"
                       placeholder="Имя друга" />
            </label>
        </div>
        <div class="modal-body friend-list-overlay">
            <ul class="t-friend-list friend-list unstyled"></ul>
        </div>
        <div class="modal-footer">
            <a href="#" class="j-popup-close btn">Закрыть</a>
            <a href="#" class="j-popup-apply btn primary">
                Выбрать
            </a>
        </div>
    </div>
</div>