<style type="text/css">


</style>

<div class="row">
    <div class="span7">
        <div class="title-image">
            <img src="/img/app/title.jpg" alt="Тортик" width="330" height="330" />
        </div>
    </div>
    <div class="span5">
        <div class="application-intro">
            <h3>Создайте дизайн <br /> Вашего торта сами!</h3>
            <p>
                Делайте тортик, пользуясь возможностями конструктора &mdash;
                сохраняйте картинку, отправляйте ее друьям. Заказывайте, при
                возможности.
            </p>
            <p>
                Знаете таких? <a href="#">Порекомендуйте нам!</a>
            </p>
            <p>
                <a class="j-selection-next btn primary large">
                    Начнем &raquo;
                </a>
            </p>
        </div>
    </div>
</div>

<hr />
        
<div class="row">
    <div class="span14 carousel cake-gallery">
        <h3>Галерея тортиков</h3>

        <ul class="j-item-selector media-grid cake-gallery-body">
            <li class="j-selection-item current">
                <a>
                    <span class="expand-item">
                        <span class="image-box image-center">
                            <img class="j-image-popup expanded-image vertical"
                                 src="/img/app/title/photo_1.jpg"
                                 alt="Фото" />
                        </span>
                    </span>
                    <span class="expand-item second">
                        <span class="image-box image-center">
                            <img class="j-image-popup expanded-image vertical"
                                 src="/img/app/title/before_1.jpg"
                                 alt="До"  />
                        </span>
                    </span>
                    <span class="expand-item third">
                        <span class="image-box image-center">
                            <img class="j-image-popup expanded-image horizontal"
                                 src="/img/app/title/after_1.jpg"
                                 alt="После" />
                        </span>
                    </span>
                </a>
            </li>

            <li class="j-selection-item">
                <a>
                    <span class="expand-item">
                        <span class="image-box image-center">
                            <img class="j-image-popup expanded-image horizontal"
                                 src="/img/app/title/photo_2.jpg"
                                 alt="Фото" />
                        </span>
                    </span>
                    <span class="expand-item second">
                        <span class="image-box image-center">
                            <img class="j-image-popup expanded-image vertical"
                                 src="/img/app/title/before_2.jpg"
                                 alt="До" />
                        </span>
                    </span>
                    <span class="expand-item third">
                        <span class="image-box image-center">
                            <img class="j-image-popup expanded-image horizontal"
                                 src="/img/app/title/after_2.jpg"
                                 alt="После" />
                        </span>
                    </span>
                </a>
            </li>

            <li class="j-selection-item">
                <a>
                    <span class="expand-item">
                        <span class="image-box image-center">
                            <img class="j-image-popup expanded-image horizontal"
                                 src="/img/app/title/photo_2.jpg"
                                 alt="Фото" />
                        </span>
                    </span>
                    <span class="expand-item second">
                        <span class="image-box image-center">
                            <img class="j-image-popup expanded-image vertical"
                                 src="/img/app/title/before_2.jpg"
                                 alt="До" />
                        </span>
                    </span>
                    <span class="expand-item third">
                        <span class="image-box image-center">
                            <img class="j-image-popup expanded-image horizontal"
                                 src="/img/app/title/after_2.jpg"
                                 alt="После" />
                        </span>
                    </span>
                </a>
            </li>

        </ul>
    </div>
</div>