<form class="j-form" target="transport_frame"
      action="/api/?method=users.login" method="post">

    <div class="overlay"></div>
    <div class="modal">
        <div class="modal-header">
            <h2>Панель управления</h2>
        </div>
        <div class="modal-body">
            <div class="j-form-message alert-message hidden"></div>
            <fieldset>
                <legend>Авторизация</legend>

                <div class="j-email-input clearfix">
                    <label for="email">Email:</label>
                    <div class="input">
                        <input id="email" name="email" size="30" type="text" />
                        <span class="j-message help-inline">
                            Ваш email адрес.
                        </span>
                    </div>
                </div>

                <div class="j-password-input clearfix">
                    <label for="password">Пароль:</label>
                    <div class="input">
                        <input id="password" name="password" size="30" type="password" />
                        <span class="help-inline">
                            <span class="j-message">Ваш пароль.</span>
                            <a href="#">Забыли?</a>
                        </span>
                    </div>
                </div>
            </fieldset>

        </div>
        <div class="modal-footer">
            <input type="submit" class="btn primary" value="Войти" />
        </div>
    </div>
</form>