<style type="text/css">

    .carousel {
        overflow-x: auto;
        overflow-y: hidden;
    }

    .carousel-body {
        margin-bottom: -10px;
        margin-top: 10px;
        width: 32000px;
    }

</style>

<div class="row">
    <div class="span8">
        <img src="" alt="" width="460" height="460" />
        
        <a class="j-selection-next btn primary large">
            Начнем &raquo;
        </a>
    </div>
    <div class="span6">
        <h2>Ваш город <span class="t-current-city"></span>?</h2>
        <span id="city_warning" class="t-city-warning">Извините, в данном городе нельзя заказать торт!</span>
        <label>
            Выбрать другой:
            <select id="city_list" class="t-city-list"></select>
        </label>

    </div>
</div>
        
<div class="row">
    <div class="j-carousel span14 carousel">
        <ul class="j-carousel-body media-grid carousel-body">
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
            <li><a class="j-carousel-item"><img src="" alt="" width="90" height="90"/></a></li>
        </ul>
    </div>
</div>

<div class="hidden" xmlns:tuna="http://localhost/tuna">
    <tuna:template id="title_template">
        <tuna:if tuna:path="is_game" tuna:ne="true"
                 tuna:target="t-city-warning" tuna:class="hidden" />

        <tuna:spot tuna:target="t-current-city"  tuna:path="user/location/city" />

        <tuna:list tuna:target="t-city-list" tuna:path="cities"
                   tuna:item-renderer-id="city_renderer"
                   tuna:item-template-id="city_template"
                   tuna:key-path="$key" />

    </tuna:template>

    <tuna:template id="city_template">
        <tuna:spot tuna:target="t-city" tuna:path="value" />
        <tuna:attr tuna:target="t-city" tuna:path="selected" tuna:name="selected" />
    </tuna:template>

    <select>
        <option id="city_renderer" class="t-city"></option>
    </select>

</div>