<script type="text/javascript" src="/js/src/rest/vk/vk-method-factory.js"></script>
<script type="text/javascript" src="/js/src/rest/vk/vk-method.js"></script>

<script type="text/javascript" src="/js/src/rest/vk/friends/get-list.js"></script>

<script type="text/javascript" src="/js/src/rest/vk/wall/post.js"></script>

<script src="http://vkontakte.ru/js/api/xd_connection.js" type="text/javascript"></script>


<script type="text/javascript">
    VK.init(function() {
        main();
    });
</script>
    
