<?php $app = $this->session->get('app') ?>

<script type="text/javascript" src="/js/src/rest/ok/ok-method-factory.js"></script>

<script type="text/javascript" src="/js/src/rest/ok/friends/get-list.js"></script>

<script type="text/javascript" src="/js/src/rest/ok/wall/post.js"></script>

<!--script src="<?php echo $app['api_server'] ?>js/fapi.js" type="text/javascript"></script-->

<script type="text/javascript">

    //FAPI.init(
     //   '<?php echo $app['api_server'] ?>',
    //    '<?php echo $app['apiconnection'] ?>',
    //    function() {
    //        FAPI.Client.initialize();
            main();
    //    }
    //);
</script>
