<script type="text/javascript" src="/js/src/rest/social/ok/users/get-current.js"></script>

<script type="text/javascript" src="/js/src/ui/modules/social/ok/friends-popup.js"></script>

<script src="<?php echo $this->request->get('api_server') ?>js/fapi.js" type="text/javascript"></script>

<script type="text/javascript">
    FAPI.init(
        '<?php echo $this->request->get('api_server') ?>',
        '<?php echo $this->request->get('apiconnection') ?>',
        function() {
            main(<?php echo json_encode($this->request->get()) ?>);
            FAPI.Client.initialize();

            var args = tuna.utils.сonfig.get('custom_args')
            if (args !== null) {
                var url = args.split('ok_cake_url=').pop().split('&').shift();
                ui.Popup.alert(
                    '<img src="http://files.fotonatorte.ru/ok-image/' +
                            url + '" alt="Мой тортик!" />'
                )
            }
        }
    );

    function API_callback(status, method, attr) {
        StreamPublish(attr);
    }

    var spMethodParams;
    function StreamPublish(resig){
        var params = spMethodParams || {};

        FAPI.Client.call(params, function(status, data, error) {
            if (status=="ok"){
                alert("Published successfully");
            } else{
                alert("ERROR : " + error.error_msg + "(" + error.error_code + ")");
            }
        }, resig);
    }

    function PrepareStreamPublish(){
        spMethodParams = {
            "method":"stream.publish",
            "message":"Sample post!"
        };


        var params = spMethodParams || {};
        params["application_key"] = FAPI.Client.applicationKey;
        params["session_key"] = FAPI.Client.sessionKey;
        params["format"] = FAPI.Client.format;

        return FAPI.Util.calcSignature(params, FAPI.Client.sessionSecretKey);
    }


</script>

<input type="button" onclick="FAPI.UI.showConfirmation('stream.publish','Application will submit news feed', PrepareStreamPublish());" value="Stream Publish">

