<script type="text/javascript" src="/public/js/src/rest/social/ok/ok-method-factory.js"></script>
<script type="text/javascript" src="/public/js/src/rest/social/ok/friends/get-list.js"></script>
<script type="text/javascript" src="/public/js/src/rest/social/ok/wall/post.js"></script>

<script src="<?php echo $this->request->get('api_server') ?>js/fapi.js" type="text/javascript"></script>

<script type="text/javascript">
    FAPI.init(
        '<?php echo $this->request->get('api_server') ?>',
        '<?php echo $this->request->get('apiconnection') ?>',
        function() {
            main();
            FAPI.Client.initialize();
        }
    );
</script>
