<div class="j-navigation container">
    <div class="content">
        <div class="page-header">
            <h1 class="main-title">
                <img class="main-logo" src="/img/logo.png"
                     alt="Фото на торте!" />

                <small>
                    <q class="main-subtitle">Дизайнерские сладости на</q>
                    <q class="main-subtitle">День святого Валентина!</q>
                </small>
            </h1>

            <?php if ($this->request->get('network') === NULL) {?>
                <script type="text/javascript" src="http://yandex.st/share/share.js"></script>
                <div id="share" class="share-block">
                    <div class="share-title">Поделитесь с друзьями:</div>
                    <div class="yashare-auto-init"
                         data-yashareL10n="ru"
                         data-yashareType="none"
                         data-yashareQuickServices="facebook,lj,odnoklassniki,vkontakte,yaru"></div>
                </div>
            <?php } ?>

        </div>


        <div id="title_step" data-init-event="ui-navigate"
             class="j-navigation-page j-transform-container row step active">

            <div class="span12">

                <?php switch ($this->request->get('campaign')) {
                    case 'vkval':
                    case 'yaval': {
                        $this->render('steps/campaign/title');
                        break;
                    }
                    default: { $this->render('steps/title'); }
                } ?>

            </div>
        </div>

        <div id="designer_step" data-init-event="ui-navigate"
             class="j-navigation-page j-transform-container row step">

             <?php $this->render('steps/designer') ?>
        </div>

        <div id="share_step" data-init-event="ui-navigate"
             class="j-navigation-page j-transform-container row step">

            <?php $this->render('steps/share') ?>
        </div>

        <div id="recipe_step" data-init-event="ui-navigate"
             data-template-id="recipe_template"
             class="j-navigation-page j-transform-container row step">

            <?php $this->render('steps/recipe') ?>
        </div>

        <div id="order_step" data-init-event="ui-navigate"
             data-template-id="order_template"
             class="j-navigation-page j-transform-container row step">

            <?php $this->render('steps/order') ?>
        </div>

        <div id="result_step" data-init-event="ui-navigate"
             class="j-navigation-page j-transform-container row step">

            <?php $this->render('steps/result') ?>
        </div>
    </div>
</div>

<div id="image_popup" class="popup">
     <div class="overlay"></div>
     <div class="modal">
         <div class="modal-header">
            <h3 class="j-alt-text"></h3>
         </div>
         <div class="modal-body">
             <img class="j-popup-image" alt="" />
         </div>
         <div class="modal-footer">
             <a href="#" class="j-popup-close btn">Закрыть</a>
         </div>
     </div>
 </div>

<div class="hide">
    <select>
        <option id="option_renderer" class="t-option"></option>
    </select>

    <ul>
        <li id="friend_item_renderer">
            <img class="t-userpic userpic" alt="Фото друга"
                 width="50" height="50"/>
            <span class="t-user-name"></span>
            <a class="t-user-id j-send-button send-cake-button pull-right">Отправить</a>
        </li>
        <li id="recipe_renderer">
            <a class="recipe-tile">
                <img class="t-recipe-img t-recipe-index j-popup j-recipe-image"
                     alt="Рецепт" width="90" height="90"
                     data-popup-selector="#recipe_description_popup"/>

                <label class="recipe-label">
                    <input class="t-recipe-input j-recipe-radio" type="radio" name="recipe_id" />
                    <span class="t-recipe-name"></span>
                </label>
            </a>
        </li>
        <li id="city_item_renderer" class="j-autocomplete-item">
           <a class="t-name"></a>
        </li>
    </ul>
</div>


<?php switch ($this->request->get('campaign')) {
   case 'vkval':{ $this->render('counters/vkval'); break; }
   case 'yaval': { $this->render('counters/yaval'); break; }
} ?>
