<div class="j-navigation container-fluid">
    <?php if ($this->request->get('network') === NULL) { ?>
        <div class="site-core">
    <?php } else { ?>
        <div class="app-core">
    <?php }?>

        <div class="row-fluid page-header">
            <div class="span6">
                <h1 class="main-title">
                    <img class="main-logo" src="/img/logo.png" alt="Фото на торте!" />

                    <small>
                        <q class="main-subtitle">
                            Дизайнерские сладости на <br />
                            День защитника Отечетва!
                        </q>
                    </small>
                </h1>
            </div>

            <div class="span6">
                <?php if ($this->request->get('network') === NULL) {?>
                    <script type="text/javascript" src="http://yandex.st/share/share.js"></script>

                    <div id="share" class="share-block">
                        <div class="yashare-auto-init"
                             data-yashareL10n="ru"
                             data-yashareType="none"
                             data-yashareQuickServices="facebook,lj,odnoklassniki,vkontakte,yaru"></div>
                        <div class="share-title"> +7 (812) 323-52-18 </div>
                    </div>
                <?php } ?>
            </div>
        </div>

        <?php $this->render('steps/title'); ?>
        <?php $this->render('steps/designer') ?>
        <?php $this->render('steps/share') ?>
        <?php $this->render('steps/recipe') ?>
        <?php $this->render('steps/order') ?>
        <?php $this->render('steps/result') ?>

    </div>
</div>


<div id="image_popup" class="hide">
     <div class="modal-backdrop"></div>
     <div class="modal">
         <div class="modal-header">
            <h3 class="j-alt-text"></h3>
         </div>
         <div class="modal-body">
             <img class="j-popup-image" alt="" />
         </div>
         <div class="modal-footer">
             <a href="#" class="j-popup-close btn">Закрыть</a>
         </div>
     </div>
 </div>

<div class="hide">
    <select>
        <option id="option_renderer" class="t-option"></option>
    </select>

    <ul>
        <li id="friend_item_renderer">
            <img class="t-userpic userpic" alt="Друг" width="50" height="50"/>

            <span class="t-user-name"></span>

            <a href="#"
               class="t-user-id j-send-button send-cake-button pull-right">
                Отправить
            </a>
        </li>
        <li id="recipe_renderer">
            <div class="recipe-tile thumbnail">
                <img class="t-recipe-img t-recipe-index j-popup-button j-recipe-image"
                     alt="Рецепт" width="90" height="90"
                     data-popup-selector="#recipe_description_popup"/>

                <label class="recipe-label">
                    <input class="t-recipe-input j-recipe-radio" type="radio" name="recipe_id" />
                    <span class="t-recipe-name"></span>
                </label>
            </div>
        </li>
        <li id="city_item_renderer" class="j-autocomplete-item">
           <a class="t-name" href="#"></a>
        </li>
    </ul>
</div>