<div class="j-navigation container-fluid">

    <?php if ($this->request->get('network') === NULL) { ?>
        <div id="site_container">
    <?php } else { ?>
        <div id="app_container">
    <?php }?>

        <div class="page-header">
            <h1 class="page-header-title">
                <img class="page-header-logo" src="/img/logo.png" alt="Фото на торте!" />

                <small class="page-header-subtitle">
                    Дизайнерские сладости на <br />
                    День защитника Отечетва!
                </small>
            </h1>


            <?php if ($this->request->get('network') === NULL) {?>

                <div class="page-header-info-block">
                    <div class="page-header-quality-block">
                        <h3>Гаратния качества профессиональной кондитерской!</h3>
                    </div>
                    <div class="page-header-delivery-block">
                        <h3>Бесплатная доставка!</h3>
                    </div>
                </div>

                <script type="text/javascript" src="http://yandex.st/share/share.js"></script>

                <div class="share-block">
                    <div class="yashare-auto-init"
                         data-yashareL10n="ru"
                         data-yashareType="none"
                         data-yashareQuickServices="facebook,lj,odnoklassniki,vkontakte,yaru"></div>
                    <div class="share-block-text"> +7 (812) 323-52-18 </div>
                </div>

            <?php } ?>
        </div>

        <?php $this->render('steps/title')    ?>
        <?php $this->render('steps/share')    ?>
        <?php $this->render('steps/order')    ?>
        <?php $this->render('steps/result')   ?>
        <?php $this->render('steps/recipe')   ?>
        <?php $this->render('steps/designer') ?>

    </div>
</div>


<div id="image_popup" class="hide">
     <div class="modal-backdrop"></div>
     <div class="modal">
         <div class="modal-header">
            <h3 class="j-alt-text"></h3>
         </div>
         <div class="modal-body">
             <img alt src class="j-popup-image" />
         </div>
         <div class="modal-footer">
             <a href="#" class="j-popup-close btn">Закрыть</a>
         </div>
     </div>
 </div>

<div class="hide">
    <select>
        <option id="option_renderer" class="t-option"></option>
    </select>

    <ul>
        <li id="friend_item_renderer">
            <img class="t-userpic userpic" alt="Друг" width="50" height="50"/>

            <span class="t-user-name"></span>

            <a href="#"
               class="t-user-id j-send-button send-cake-button pull-right">
                Отправить
            </a>
        </li>
        <li id="recipe_renderer">
            <div class="recipe-tile thumbnail">
                <img class="t-recipe-img t-recipe-index j-popup-button j-recipe-image"
                     alt="Рецепт" width="90" height="90"
                     data-popup-selector="#recipe_description_popup"/>

                <label class="recipe-label">
                    <input class="t-recipe-input j-recipe-radio" type="radio" name="recipe_id" />
                    <span class="t-recipe-name"></span>
                </label>
            </div>
        </li>
        <li id="city_item_renderer" class="j-autocomplete-item">
           <a class="t-name" href="#"></a>
        </li>
    </ul>
</div>

