<meta http-equiv="Content-Type" content="Type=text/html; charset=utf-8">

<title>Фото на торте</title>

<link rel="stylesheet" type="text/css" href="/css/bootstrap.css" />

<link rel="stylesheet" type="text/css" href="/css/typography.css" />
<link rel="stylesheet" type="text/css" href="/css/layout.css" />

<link rel="stylesheet" type="text/css" href="/css/head.css" />
<link rel="stylesheet" type="text/css" href="/css/share.css" />

<link rel="stylesheet" type="text/css" href="/css/title-step.css" />

<link rel="stylesheet" type="text/css" href="/css/styles.css" />
