<script type="text/javascript" src="/js/common.js"></script>

<script type="text/javascript">
    var APP_NETWORK = '<?php echo $this->request->get('network') ?>';

    function main() {
        tuna.dom.setSelectorEngine(jQuery.find);

        tuna.model.setDefaultStorage(new tuna.model.DataStorage());

        var container = new tuna.ui.container.TransformContainer(document.body);
        container.init();
    }
</script>

<?php switch ($this->request->get('network')) {
    case 'vk': { $this->render('scripts/vk'); break; }
    case 'ok': { $this->render('scripts/ok'); break; }
    default: ?> <script type="text/javascript">main();</script> <?php
} ?>