<div class="row">
    <div class="span7">
        <ul class="campaign-list media-grid">
            <li><a>
                    <span class="cake">
                        <img src="http://files.fotonatorte.ru/cake_image_4f2be2cece250.jpg" alt="Тортик"
                             width="110" height="110" />
                        <span class="cake-price">1200 руб.</span>
                    </span>

                    <span class="cake-info">
                        <span class="">1 кг.</span>
                        <span class="j-navigation-link btn small pull-right primary"
                              data-href="order_step"
                              data-campaign="<?php echo $this->request->get('campaign') ?>"
                              data-weight="1" data-price="1200"
                              data-image="http://files.fotonatorte.ru/cake_image_4f2be2cece250.jpg">
                            Хочу!
                        </span>
                    </span>
            </a></li>
            <li><a>
                    <span class="cake">
                        <img src="http://files.fotonatorte.ru/cake_image_4f2be1b0f23b5.jpg" alt="Тортик"
                             width="110" height="110" />
                        <span class="cake-price">1200 руб.</span>
                    </span>

                    <span class="cake-info">
                        <span class="">1 кг.</span>
                        <span class="j-navigation-link btn small pull-right primary"
                              data-href="order_step"
                              data-campaign="<?php echo $this->request->get('campaign') ?>"
                              data-weight="1" data-price="1200"
                              data-image="http://files.fotonatorte.ru/cake_image_4f2be1b0f23b5.jpg">
                            Хочу!
                        </span>
                    </span>
            </a></li>
            <li><a>
                    <span class="cake">
                        <img src="http://files.fotonatorte.ru/cake_image_4f2bc82f697f6.jpg" alt="Тортик"
                             width="110" height="110" />
                        <span class="cake-price">1200 руб.</span>
                    </span>

                    <span class="cake-info">
                        <span class="">1 кг.</span>
                        <span class="j-navigation-link btn small pull-right primary"
                              data-href="order_step"
                              data-campaign="<?php echo $this->request->get('campaign') ?>"
                              data-weight="1" data-price="1200"
                              data-image="http://files.fotonatorte.ru/cake_image_4f2bc82f697f6.jpg">
                            Хочу!
                        </span>
                    </span>
            </a></li>
            <li><a>
                    <span class="cake">
                        <img src="http://files.fotonatorte.ru/cake_image_4f2bc95f7dac5.jpg" alt="Тортик"
                             width="110" height="110" />
                        <span class="cake-price">1200 руб.</span>
                    </span>

                    <span class="cake-info">
                        <span class="">1 кг.</span>
                        <span class="j-navigation-link btn small pull-right primary"
                              data-href="order_step"
                              data-campaign="<?php echo $this->request->get('campaign') ?>"
                              data-weight="1" data-price="1200"
                              data-image="http://files.fotonatorte.ru/cake_image_4f2bc95f7dac5.jpg">
                            Хочу!
                        </span>
                    </span>
            </a></li>
            <li><a>
                    <span class="cake">
                        <img src="http://files.fotonatorte.ru/cake_image_4f2bc96a989c4.jpg" alt="Тортик"
                             width="110" height="110" />
                        <span class="cake-price">1200 руб.</span>
                    </span>

                    <span class="cake-info">
                        <span class="">1 кг.</span>
                        <span class="j-navigation-link btn small pull-right primary"
                              data-href="order_step"
                              data-campaign="<?php echo $this->request->get('campaign') ?>"
                              data-weight="1" data-price="1200"
                              data-image="http://files.fotonatorte.ru/cake_image_4f2bc96a989c4.jpg">
                            Хочу!
                        </span>
                    </span>
            </a></li>
            <li><a>
                    <span class="cake">
                        <img src="http://files.fotonatorte.ru/cake_image_4f2bcb378cda3.jpg" alt="Тортик"
                             width="110" height="110" />
                        <span class="cake-price">1200 руб.</span>
                    </span>

                    <span class="cake-info">
                        <span class="">1 кг.</span>
                        <span class="j-navigation-link btn small pull-right primary"
                              data-href="order_step"
                              data-campaign="<?php echo $this->request->get('campaign') ?>"
                              data-weight="1" data-price="1200"
                              data-image="http://files.fotonatorte.ru/cake_image_4f2bcb378cda3.jpg">
                            Хочу!
                        </span>
                    </span>
            </a></li>
            <li><a>
                    <span class="cake">
                        <img src="http://files.fotonatorte.ru/cake_image_4f2bcf835adb9.jpg" alt="Тортик"
                             width="110" height="110" />
                        <span class="cake-price">1200 руб.</span>
                    </span>

                    <span class="cake-info">
                        <span class="">1 кг.</span>
                        <span class="j-navigation-link btn small pull-right primary"
                              data-href="order_step"
                              data-campaign="<?php echo $this->request->get('campaign') ?>"
                              data-weight="1" data-price="1200"
                              data-image="http://files.fotonatorte.ru/cake_image_4f2bcf835adb9.jpg">
                            Хочу!
                        </span>
                    </span>
            </a></li>
            <li><a>
                    <span class="cake">
                        <img src="http://files.fotonatorte.ru/cake_image_4f2bd21f5b193.jpg" alt="Тортик"
                             width="110" height="110" />
                        <span class="cake-price">1200 руб.</span>
                    </span>

                    <span class="cake-info">
                        <span class="">1 кг.</span>
                        <span class="j-navigation-link btn small pull-right primary"
                              data-href="order_step"
                              data-campaign="<?php echo $this->request->get('campaign') ?>"
                              data-weight="1" data-price="1200"
                              data-image="http://files.fotonatorte.ru/cake_image_4f2bd21f5b193.jpg">
                            Хочу!
                        </span>
                    </span>
            </a></li>
            <li><a>
                    <span class="cake">
                        <img src="http://files.fotonatorte.ru/cake_image_4f2bd57a52b6e.jpg" alt="Тортик"
                             width="110" height="110" />
                        <span class="cake-price">3000 руб.</span>
                    </span>

                    <span class="cake-info">
                        <span class="">2 кг.</span>
                        <span class="j-navigation-link btn small pull-right primary"
                              data-href="order_step"
                              data-campaign="<?php echo $this->request->get('campaign') ?>"
                              data-weight="2" data-price="3000"
                              data-image="http://files.fotonatorte.ru/cake_image_4f2bd57a52b6e.jpg">
                            Хочу!
                        </span>
                    </span>
            </a></li>



        </ul>



    </div>
    <div class="span4 intro">
        <div class="application-intro">
            <h3>Поздравьте любимых оригинально!</h3>
            <p>
                Никогда не пекли тортики? Ничего, мы с удовольствием подготовим
                оригинальную валентинку за вас!
                <br />
                Изображение на торте съедобно! Доставка и упаковка включены в
                цену!

                Заказы так же принимаем по телефону <b>8 (812) 323-52-18</b> и
                по почте <b>visser@creat-present.ru</b>!
            </p>

            <p class="detailed-comment">
                Не нашли подходящего тортика? Сконструируйте свой!
            </p>
            <p>
                <a class="j-navigation-link btn primary large"
                   data-href="designer_step">
                    Начнем &raquo;
                </a>
            </p>
            <p class="detailed-comment">
                Мы изготовим тортик с загруженным вами изображением!
            </p>
        </div>
    </div>
</div>

<hr />
        
<div class="row">
    <div class="span14 carousel cake-gallery">
        <h3>Галерея тортиков <small>(наведите мышку)</small></h3>
        <h4><a class="j-cake-image-popup" data-cake-index="4">
            Как мы это делаем?
        </a></h4>
        
        <ul class="j-selection-group media-grid cake-gallery-body"
            data-selection-event="mouseover">

            <li class="j-selection-item active j-cake-image-popup"
                data-cake-index="1">

                <a>
                    <span class="expand-item">
                        <span class="image-box image-center">
                            <img class="expanded-image vertical" alt="Фото"
                                 src="/img/title/photo_small_1.jpg" />
                        </span>
                    </span>
                    <span class="expand-item second">
                        <span class="image-box image-center">
                            <img class="expanded-image vertical" alt="До"
                                 src="/img/title/before_small_1.jpg" />
                        </span>
                    </span>
                    <span class="expand-item third">
                        <span class="image-box image-center">
                            <img class="expanded-image horizontal" alt="После"
                                 src="/img/title/after_small_1.jpg" />
                        </span>
                    </span>
                </a>
            </li>

            <li class="j-selection-item j-cake-image-popup" data-cake-index="2">
                <a>
                    <span class="expand-item">
                        <span class="image-box image-center">
                            <img class="expanded-image horizontal" alt="Фото"
                                 src="/img/title/photo_small_2.jpg" />
                        </span>
                    </span>
                    <span class="expand-item second">
                        <span class="image-box image-center">
                            <img class="expanded-image vertical" alt="До"
                                 src="/img/title/before_small_2.jpg" />
                        </span>
                    </span>
                    <span class="expand-item third">
                        <span class="image-box image-center">
                            <img class="expanded-image horizontal" alt="После"
                                 src="/img/title/after_small_2.jpg"  />
                        </span>
                    </span>
                </a>
            </li>

            <li class="j-selection-item j-cake-image-popup" data-cake-index="3">
                <a>
                    <span class="expand-item">
                        <span class="image-box image-center">
                            <img class="expanded-image vertical" alt="Фото"
                                 src="/img/title/photo_small_3.jpg" />
                        </span>
                    </span>
                    <span class="expand-item second">
                        <span class="image-box image-center">
                            <img class="expanded-image horizontal" alt="До"
                                 src="/img/title/before_small_3.jpg" />
                        </span>
                    </span>
                    <span class="expand-item third">
                        <span class="image-box image-center">
                            <img class="expanded-image vertical" alt="После"
                                 src="/img/title/after_small_3.jpg" />
                        </span>
                    </span>
                </a>
            </li>

        </ul>
    </div>
</div>

<div id="cake_image_popup" class="popup">
     <div class="overlay"></div>
     <div class="modal">
         <div class="modal-header">
            <h3>Тортик до и после</h3>
         </div>
         <div class="modal-body">
             <div class="image-container">
                 <img class="j-cake-image-photo" alt="Фото" />
                 <img class="j-cake-image-before" alt="До" />
                 <img class="j-cake-image-after" alt="После" />
             </div>
         </div>
         <div class="modal-footer">
             <a href="#" class="j-popup-close btn">Закрыть</a>
         </div>
     </div>
 </div>